#!/usr/bin/env python3
"""Pre-compute the docs QR code as a C bitmap.

The URL never changes, so the code is generated here and committed rather
than encoded on the RP2040: a QR encoder would cost far more flash and code
than the 185-byte bitmap it would produce.

    pip install segno
    python3 tools/make_qr.py > rp/src/include/oric_qr_docs.h
"""
import sys
import segno

URL = ("https://docs.sidecartridge.com/sidecartridge-multidevice"
       "/microfirmwares/oric-emulator/")

q = segno.make(URL, error="L", micro=False)
m = [[1 if c else 0 for c in row] for row in q.matrix]
n = len(m)
stride = (n + 7) // 8

out = sys.stdout
out.write("#pragma once\n")
out.write("// QR code for the Oric emulator setup page:\n")
out.write(f"//   {URL}\n")
out.write("//\n")
out.write("// Generated by tools/make_qr.py -- do not edit by hand. The URL is fixed,\n")
out.write("// so the code is pre-computed: a QR encoder on the RP2040 would cost far\n")
out.write("// more flash than this bitmap. Error correction L is plenty for a screen,\n")
out.write("// which cannot get dirty or torn.\n")
out.write("//\n")
out.write("// One bit per module, MSB of each byte is the leftmost module of the row.\n")
out.write("// The quiet zone is NOT included; the drawing code adds it.\n\n")
out.write("#include <stdint.h>\n\n")
out.write(f"#define ORIC_QR_MODULES {n}\n")
out.write(f"#define ORIC_QR_STRIDE {stride}\n\n")
out.write(f"static const uint8_t oric_qr_docs[ORIC_QR_MODULES * ORIC_QR_STRIDE] = {{\n")
for r in range(n):
    row = m[r]
    by = []
    for b in range(stride):
        v = 0
        for k in range(8):
            i = b * 8 + k
            if i < n and row[i]:
                v |= 0x80 >> k
        by.append(v)
    out.write("    " + ", ".join(f"0x{v:02X}" for v in by) + ",\n")
out.write("};\n")
